version: '3.9'

services:
  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${REACT_APP_ENV}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ENV=${REACT_APP_ENV}
