version: '3.9'

services:
  flask_prod:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env.production
    environment:
      FLASK_URL: http://192.168.1.203:5001
      MONGODB_URL: mongodb://mongo:27017/  # Use the service name for MongoDB connection
    depends_on:
      - mongo  # Ensure MongoDB starts before Flask      

  react_prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    environment:
      REACT_APP_URL: http://192.168.1.203:5001
      
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: